name: dbt CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dbt
      run: pip install dbt-core
    - name: Run dbt tests
      run: dbt test --profiles-dir '04-analytics-engineering /taxi_rides_ny'
      working-directory: '04-analytics-engineering /taxi_rides_ny'
    - name: Run dbt models
      run: dbt run --profiles-dir '04-analytics-engineering /taxi_rides_ny'
      working-directory: '04-analytics-engineering /taxi_rides_ny'
