name: dbt CI/CD

on:
  push:
    paths:
      - '04-analytics-engineering /taxi_rides_ny'
  pull_request:
    paths:
      - '04-analytics-engineering /taxi_rides_ny'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dbt
      run: pip install dbt-core
    - name: Run dbt tests
      run: dbt test
    - name: Run dbt models
      run: dbt run
